import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

js_code = """const API={async get(u){const r=await fetch(u);return r.json()},async post(u,b){const r=await fetch(u,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(b)});return r.json()}};
let M=null,C=null,R=[],P=[],S=[],KD={},currentRpe={};
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.getElementById(id).classList.add("active");window.scrollTo(0,0)}
function updateNav(){const n=document.getElementById("topNav"),u=document.getElementById("navUser"),c=document.getElementById("navCoachUser");if(C||M)n.style.display="flex";else{n.style.display="none";return}if(C){u.style.display="none";c.style.display="flex";document.getElementById("navCoachAvatar").textContent=C.avatar;document.getElementById("navCoachName").textContent=C.name;return}c.style.display="none";u.style.display="flex";document.getElementById("navUserAvatar").textContent=M.avatar;document.getElementById("navUserName").textContent=M.name}
function switchLoginTab(t){document.querySelectorAll(".login-page-tab").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".login-page-form").forEach(f=>f.classList.remove("active"));if(t==="member"){document.getElementById("tabMemberBtn").classList.add("active");document.getElementById("formMember").classList.add("active")}else{document.getElementById("tabCoachBtn").classList.add("active");document.getElementById("formCoach").classList.add("active")}}

// === Login ===
async function handleLogin(){const p=document.getElementById("loginPhone").value.trim();if(p.length<11){document.getElementById("loginPhone").style.borderColor="#ff4444";return}document.getElementById("loginPhone").style.borderColor="";try{const d=await API.post("/api/login",{phone:p});if(d.success){M=d.member;C=null;localStorage.setItem("fitness_member",JSON.stringify(d.member));localStorage.setItem("fitness_phone",p);localStorage.removeItem("fitness_coach");updateNav();renderMember();showPage("page-member")}}catch(e){alert("\\u767b\\u5f55\\u5931\\u8d25")}}
async function handleCoachLogin(){const p=document.getElementById("coachLoginPhone").value.trim();if(p.length<11){document.getElementById("coachLoginPhone").style.borderColor="#ff4444";return}document.getElementById("coachLoginPhone").style.borderColor="";try{const d=await API.post("/api/coach/login",{phone:p});if(d.success){C=d.coach;M=null;localStorage.setItem("fitness_coach",JSON.stringify(d.coach));localStorage.removeItem("fitness_member");localStorage.removeItem("fitness_phone");updateNav();renderCoachDash();showPage("page-coach-dash")}else alert("\\u8d26\\u53f7\\u4e0d\\u5b58\\u5728")}catch(e){alert("\\u767b\\u5f55\\u5931\\u8d25")}}
function logout(){M=null;C=null;localStorage.removeItem("fitness_member");localStorage.removeItem("fitness_phone");localStorage.removeItem("fitness_coach");updateNav();showPage("page-login")}

// === Coach Dashboard ===
function renderCoachDash(){if(!C)return;const c=C;document.getElementById("coachDashAvatar").textContent=c.avatar;document.getElementById("coachDashName").textContent=c.name;document.getElementById("coachDashBadge").textContent=c.badge;const e=document.getElementById("coachMemberList");if(!c.members.length){e.innerHTML='<div class="record-empty">\\u6682\\u65e0\\u5b66\\u5458</div>';return}e.innerHTML=c.members.map(m=>'<div class="coach-member-card" onclick="openCoachMemberModal(\\''+m.phone+'\\')"><div class="coach-member-avatar">'+m.avatar+'</div><div class="coach-member-info"><div class="coach-member-name">'+m.name+'</div><div class="coach-member-meta">\\u5165\\u4f1a '+m.member_since+' \\u00b7 '+m.total_sessions+'\\u6b21\\u8bfe</div></div><div class="coach-member-arrow">\\u203a</div></div>').join("")}
let SMP=null;
async function openCoachMemberModal(mp){SMP=mp;document.getElementById("coachMemberModal").classList.add("active");document.body.style.overflow="hidden";const m=C.members.find(x=>x.phone===mp);const e=document.getElementById("coachMemberDetail");e.innerHTML='<div class="coach-detail-sheet-header"><div class="coach-detail-sheet-avatar">'+(m?m.avatar:"\\U0001f464")+'</div><div><div class="coach-detail-sheet-name">'+(m?m.name:"\\u5b66\\u5458")+'</div><div class="coach-detail-sheet-meta">'+(m?m.member_since+" \\u00b7 "+m.total_sessions+"\\u6b21\\u8bfe":"")+'</div></div></div><div class="coach-write-section"><div class="coach-write-title">\\U0001f4cb \\u5199\\u8bad\\u7ec3\\u8ba1\\u5212</div><textarea class="coach-write-textarea" id="coachPlanInput" rows="3" placeholder="\\u5199\\u4e0b\\u8bad\\u7ec3\\u8ba1\\u5212..."></textarea><button class="coach-write-btn coach-write-btn-plan" onclick="saveCoachPlan()" style="margin-top:8px">\\u4fdd\\u5b58\\u8bad\\u7ec3\\u8ba1\\u5212</button></div><div class="coach-write-section"><div class="coach-write-title">\\U0001f4dd \\u5199\\u8bfe\\u540e\\u5c0f\\u7ed3</div><div class="coach-write-input-row"><input type="text" id="coachRecordType" placeholder="\\u7c7b\\u578b" value="\\u79c1\\u6559\\u8bfe"><input type="text" id="coachRecordDuration" placeholder="\\u65f6\\u957f" value="60min"></div><textarea class="coach-write-textarea" id="coachRecordContent" rows="2" placeholder="\\u8bad\\u7ec3\\u5185\\u5bb9..."></textarea><textarea class="coach-write-textarea" id="coachRecordSummary" rows="2" placeholder="\\u6559\\u7ec3\\u70b9\\u8bc4..." style="margin-top:8px;min-height:60px"></textarea><button class="coach-write-btn coach-write-btn-record" onclick="saveCoachRecord()">\\u4fdd\\u5b58\\u8bfe\\u540e\\u5c0f\\u7ed3</button></div><div class="coach-history-title">\\U0001f534 \\u75b2\\u52b3\\u72b6\\u6001\\uff08\\u52a0\\u8f7d\\u4e2d...\\uff09</div><div id="coachGripStatus"></div><div class="coach-history-title">\\U0001f4dc \\u5386\\u53f2\\u8bb0\\u5f55\\uff08\\u52a0\\u8f7d\\u4e2d...\\uff09</div><div id="coachMemberHistory"></div>';await loadCoachMemberData(mp);loadCoachGripData(mp)}
function closeCoachMemberModal(){document.getElementById("coachMemberModal").classList.remove("active");document.body.style.overflow="";SMP=null}
document.getElementById("coachMemberModal")&&document.getElementById("coachMemberModal").addEventListener("click",e=>{if(e.target===e.currentTarget)closeCoachMemberModal()});
async function loadCoachMemberData(mp){try{const d=await API.post("/api/coach/member/records",{phone:mp});KD[mp]=d;renderCoachMemberHistory(mp)}catch(e){}}
function renderCoachMemberHistory(mp){const d=KD[mp],e=document.getElementById("coachMemberHistory");if(!d||(!d.records.length&&!d.plans.length)){e.innerHTML='<div class="record-empty">\\u6682\\u65e0\\u8bb0\\u5f55</div>';return}let h="";if(d.plans&&d.plans.length){h+='<div style="font-size:12px;color:#4b88ff;margin:8px 0 6px">\\U0001f4cb \\u8bad\\u7ec3\\u8ba1\\u5212</div>';[...d.plans].reverse().forEach(p=>{h+='<div class="coach-history-plan"><div class="date">'+p.date+" \\u00b7 "+p.status+'</div><div class="content">'+p.content+'</div></div>'})}if(d.records&&d.records.length){h+='<div style="font-size:12px;color:#ff6b35;margin:12px 0 6px">\\U0001f4dd \\u8bad\\u7ec3\\u8bb0\\u5f55</div>';d.records.slice(0,10).forEach(r=>{const ic=r.mood==="\\U0001f4dd \\u6559\\u7ec3\\u8bb0\\u5f55";h+='<div class="record-card"><div class="record-card-header"><div class="record-date">'+r.date+'</div><div class="record-meta"><span class="record-type">'+r.type+'</span><span class="record-duration">'+r.duration+'</span>'+(ic?'<span class="record-source-coach">\\u6559\\u7ec3</span>':'')+'</div></div><div class="record-mood">'+r.mood+'</div>'+(r.content?'<div class="record-content">'+r.content+'</div>':'')+(r.summary?'<div class="record-summary"><div class="record-summary-label">\\U0001f4dd \\u6559\\u7ec3\\u70b9\\u8bc4</div>'+r.summary+'</div>':'')+'</div>'})}e.innerHTML=h}
async function loadCoachGripData(mp){try{const d=await API.post("/api/coach/member/grip",{phone:mp});const e=document.getElementById("coachGripStatus");if(d.fatigue_status){const s=d.fatigue_status;e.innerHTML='<div style="background:rgba(255,255,255,0.02);border-radius:14px;padding:16px;text-align:center;margin-bottom:16px"><div style="font-size:36px;margin-bottom:4px">'+s.icon+'</div><div style="font-size:18px;font-weight:700;color:'+s.color+'">'+s.label+'</div><div style="font-size:13px;color:rgba(255,255,255,0.3)">\\u5f53\\u524d\\u63e1\\u529b\\u4e3a\\u57fa\\u7ebf\\u7684 '+s.ratio+'%</div></div>'}else e.innerHTML='<div class="record-empty" style="padding:20px">\\u6682\\u65e0\\u75b2\\u52b3\\u6570\\u636e</div>'}catch(e){}}
async function saveCoachPlan(){const c=document.getElementById("coachPlanInput").value.trim();if(!c||!SMP||!C)return;await API.post("/api/coach/plan/save",{phone:C.phone,member_phone:SMP,content:c});document.getElementById("coachPlanInput").value="";await loadCoachMemberData(SMP)}
async function saveCoachRecord(){if(!SMP||!C)return;const t=document.getElementById("coachRecordType").value.trim()||"\\u79c1\\u6559\\u8bfe",d=document.getElementById("coachRecordDuration").value.trim()||"60min",c=document.getElementById("coachRecordContent").value.trim(),s=document.getElementById("coachRecordSummary").value.trim();if(!c&&!s){alert("\\u8bf7\\u586b\\u5199\\u5185\\u5bb9");return}await API.post("/api/coach/record/add",{phone:C.phone,member_phone:SMP,type:t,duration:d,content:c,summary:s});document.getElementById("coachRecordContent").value="";document.getElementById("coachRecordSummary").value="";await loadCoachMemberData(SMP)}

// === Member Center ===
function renderMember(){if(!M)return;const m=M;document.getElementById("memberAvatar").textContent=m.avatar;document.getElementById("memberName").textContent=m.name;document.getElementById("memberSince").textContent=m.member_since;document.getElementById("memberTrainer").textContent=m.trainer;document.getElementById("memberSessions").textContent=m.total_sessions;switchTab("records");loadRecords();loadPhotos();loadStrength();loadGrip();loadNutrition()}
async function loadRecords(){const p=localStorage.getItem("fitness_phone");if(!p)return;try{const[d,r]=await Promise.all([API.post("/api/member/records",{phone:p}),API.post("/api/member/rpe/list",{phone:p})]);R=d.records||[];currentRpe=r.rpe||{};renderRecords()}catch(e){}}
function renderRecords(){const e=document.getElementById("recordList");if(!R.length){e.innerHTML='<div class="record-empty">\\u6682\\u65e0\\u8bad\\u7ec3\\u8bb0\\u5f55 \\U0001f4aa</div>';return}e.innerHTML=R.map(r=>{const ic=r.mood==="\\U0001f4dd \\u6559\\u7ec3\\u8bb0\\u5f55";const rp=currentRpe[r.date]||0;return '<div class="record-card"><div class="record-card-header"><div class="record-date">'+r.date+'</div><div class="record-meta"><span class="record-type">'+r.type+'</span><span class="record-duration">'+r.duration+'</span>'+(ic?'<span class="record-source-coach">\\u6559\\u7ec3</span>':'')+'</div></div><div class="record-mood">'+r.mood+'</div><div class="record-content">'+r.content+'</div><div class="rpe-label">\\u8bad\\u7ec3\\u75b2\\u52b3\\u5ea6\\uff08RPE\\uff09</div><div class="rpe-row">'+[1,2,3,4,5,6,7,8,9,10].map(n=>{let c="rpe-btn";if(n>=8)c+=" rpe-high";else if(n>=5)c+=" rpe-mid";else c+=" rpe-low";if(rp===n)c+=" selected";return '<button class="'+c+'" onclick="saveRpe(\\''+r.date+'\\','+n+')">'+n+'</button>'}).join("")+'</div>'+(rp?'<div class="rpe-saved">\\u2713 \\u5df2\\u8bc4 RPE '+rp+'</div>':'<div class="rpe-hint"><span>\\u8f7b\\u677e</span><span>\\u9002\\u4e2d</span><span>\\u6781\\u9650</span></div>')+'</div>'}).join("")}
async function saveRpe(date,val){const p=localStorage.getItem("fitness_phone");if(!p)return;await API.post("/api/member/rpe/save",{phone:p,date:date,value:val});currentRpe[date]=val;renderRecords()}

// === Grip / Fatigue ===
async function handleGripSubmit(){const p=localStorage.getItem("fitness_phone");if(!p)return;const v=parseFloat(document.getElementById("gripInput").value);if(!v||v<=0){document.getElementById("gripInput").style.borderColor="#ff4444";return}document.getElementById("gripInput").style.borderColor="";const n=document.getElementById("gripNote").value.trim();await API.post("/api/member/grip/add",{phone:p,value:v,morning_note:n});document.getElementById("gripInput").value="";document.getElementById("gripNote").value="";await loadGrip()}
async function loadGrip(){const p=localStorage.getItem("fitness_phone");if(!p)return;try{const[g,cv]=await Promise.all([API.post("/api/member/grip/list",{phone:p}),API.post("/api/member/fatigue/curve",{phone:p})]);renderGripStatus(g.fatigue_status);renderGripList(g.grip);renderCurve(cv.curve||[])}catch(e){}}
function renderGripStatus(s){const e=document.getElementById("gripStatusContainer");if(!s){e.innerHTML="";return}e.innerHTML='<div class="grip-status-card"><div class="grip-status-icon">'+s.icon+'</div><div class="grip-status-label" style="color:'+s.color+'">'+s.label+'</div><div class="grip-status-detail">\\u5f53\\u524d\\u63e1\\u529b '+s.ratio+'% \\u00b7 \\u57fa\\u7ebf '+s.baseline+'kg</div><div class="grip-status-bar"><div class="grip-status-bar-fill" style="width:'+Math.min(s.ratio,100)+'%;background:'+s.color+'"></div></div></div>'}
function renderGripList(data){const e=document.getElementById("gripList");if(!data||!data.length){e.innerHTML='<div class="record-empty">\\u8fd8\\u6ca1\\u6709\\u8bb0\\u5f55\\uff0c\\u6bcf\\u5929\\u65e9\\u4e0a\\u6d4b\\u4e00\\u6b21\\u5427 \\U0001f91a</div>';return}e.innerHTML=data.slice(0,20).map(g=>'<div class="grip-history-card"><div class="grip-history-left"><div><div class="grip-history-value">'+g.value+'<span class="unit"> kg</span></div></div><div><div class="grip-history-meta">'+g.date+" "+g.time+'</div>'+(g.morning_note?'<div class="grip-history-note">'+g.morning_note+'</div>':'')+'</div></div><button class="grip-history-del" onclick="deleteGrip('+g.id+')">\\u5220\\u9664</button></div>').join("")}
async function deleteGrip(id){const p=localStorage.getItem("fitness_phone");if(!p||!confirm("\\u786e\\u5b9a\\u5220\\u9664\\uff1f"))return;await API.post("/api/member/grip/delete",{phone:p,id});await loadGrip()}

// === Fatigue Curve ===
function renderCurve(curve){const el=document.getElementById("curveChart");if(!el)return;if(!curve||curve.length<2){el.innerHTML='<div class="curve-empty">\\u8bb0\\u5f55\\u63e1\\u529b\\u548cRPE\\u540e\\u81ea\\u52a8\\u751f\\u6210 \\U0001f4ca</div>';return}let h='<table class="curve-table"><tr><td class="curve-row-label"></td>';curve.forEach(c=>{h+='<td class="date-label">'+c.date.slice(5)+"</td>"});h+='</tr><tr><td class="curve-row-label">\\u270a</td>';curve.forEach(c=>{if(c.grip){let cl="#22c55e";if(c.grip._fatigue==="high")cl="#ef4444";else if(c.grip._fatigue==="mild")cl="#eab308";h+='<td><div class="curve-grip-dot" style="background:'+cl+'">'+Math.round(c.grip.value)+"</div></td>"}else h+='<td><div class="curve-grip-value">-</div></td>'});h+='</tr><tr><td class="curve-row-label">RPE</td>';curve.forEach(c=>{if(c.rpe)h+='<td><div class="curve-rpe-dot">'+c.rpe+"</div></td>";else h+='<td><span class="curve-rpe-empty">-</span></td>'});h+="</tr></table>";el.innerHTML=h}

// === Nutrition ===
async function loadNutrition(){loadNutritionGuides();loadMeals();load52Track()}
const DAYS_CN=["\\u4e00","\\u4e8c","\\u4e09","\\u56db","\\u4e94","\\u516d","\\u65e5"];const DAYS_EN=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"];
async function load52Track(){const p=localStorage.getItem("fitness_phone");if(!p)return;try{const d=await API.post("/api/member/52track/get",{phone:p});render52Tracker(d.track||{})}catch(e){}}
let current52Track={};
function render52Tracker(track){current52Track=track;const w=document.getElementById("f52Week"),n=document.getElementById("f52Note");if(!w)return;const t=new Date().getDay(),ti=t===0?6:t-1;w.innerHTML=DAYS_EN.map((d,i)=>{const s=track[d]||"normal",it=i===ti;return '<div class="f52-day '+s+(it?" today":'')+'" onclick="toggle52Day(\\''+d+'\\')"><span class="day-label">'+(it?"\\u4eca\\u5929":"\\u5468"+DAYS_CN[i])+'</span><span class="day-icon">'+(s==="fast"?"\\U0001f34e":"\\u2705")+"</span></div>"}).join("");const fd=DAYS_EN.filter(d=>track[d]==="fast").length;if(fd===0)n.textContent="\\U0001f4a1 \\u70b9\\u51fb\\u9009\\u62e9\\u4f60\\u7684\\u65ad\\u98df\\u65e5\\uff08\\u63a8\\u8350\\u90092\\u5929\\uff09";else if(fd===2)n.textContent="\\u2705 \\u672c\\u5468 "+DAYS_EN.map((d,i)=>track[d]==="fast"?"\\u5468"+DAYS_CN[i]:"").filter(Boolean).join("\\u3001")+" \\u65ad\\u98df \\u2713";else n.textContent="\\U0001f44d \\u5df2\\u9009 "+fd+" \\u5929\\uff0c\\u5efa\\u8bae\\u90092\\u5929\\u6548\\u679c\\u6700\\u4f73"}
async function toggle52Day(d){const p=localStorage.getItem("fitness_phone");if(!p)return;current52Track[d]=current52Track[d]==="fast"?"normal":"fast";render52Tracker(current52Track);await API.post("/api/member/52track/save",{phone:p,track:current52Track})}
function scrollToGuide(id){const el=document.getElementById("guideContent"+id);if(el){el.closest(".nutrition-guide-card")?.classList.add("open");el.scrollIntoView({behavior:"smooth",block:"center"})}else{loadNutritionGuides().then(()=>setTimeout(()=>{const e2=document.getElementById("guideContent"+id);if(e2){e2.closest(".nutrition-guide-card")?.classList.add("open");e2.scrollIntoView({behavior:"smooth",block:"center"})}},200))}}
async function loadNutritionGuides(){const e=document.getElementById("nutritionGuideList");if(!e)return;try{const d=await API.get("/api/nutrition/guides");e.innerHTML=d.guides.map(g=>'<div class="nutrition-guide-card" onclick="toggleGuide('+g.id+')"><div class="nutrition-guide-header"><span class="nutrition-guide-icon">'+g.icon+'</span><span class="nutrition-guide-info"><span class="nutrition-guide-title">'+g.title+'</span><span class="nutrition-guide-summary">'+g.summary+'</span></span><span class="nutrition-guide-arrow">\\u203a</span></div><div class="nutrition-guide-content" id="guideContent'+g.id+'">'+g.content+'</div></div>').join("")}catch(e){}}
function toggleGuide(id){document.getElementById("guideContent"+id).closest(".nutrition-guide-card")?.classList.toggle("open")}
async function handleMealSave(){const p=localStorage.getItem("fitness_phone");if(!p)return;const el=document.getElementById("mealInput"),m=(el.innerText||el.textContent||"").trim();if(!m){alert("\\u8bf7\\u8bb0\\u5f55\\u996e\\u98df\\u5185\\u5bb9");return}const lines=m.split("\\n").filter(l=>l.trim()),meals=lines.map(l=>{const parts=l.split("\\uff1a");return{meal_type:parts[0].trim()||"\\u9910",foods:parts[1]?parts[1].trim():l.trim()}});await API.post("/api/member/meals/save",{phone:p,meals:meals,note:""});el.innerHTML="";await loadMeals()}
async function loadMeals(){const p=localStorage.getItem("fitness_phone");if(!p)return;try{const d=await API.post("/api/member/meals/list",{phone:p});renderMeals(d.meals||[])}catch(e){}}
function renderMeals(data){const e=document.getElementById("mealList");if(!data||!data.length){e.innerHTML='<div class="record-empty">\\u8fd8\\u6ca1\\u6709\\u996e\\u98df\\u8bb0\\u5f55 \\U0001f957</div>';return}e.innerHTML=[...data].reverse().slice(0,10).map(m=>'<div class="meal-entry"><div class="meal-entry-header"><span class="date">'+m.date+'</span></div><div>'+(m.meals||[]).map(m2=>'<span class="meal-tag">'+(m2.meal_type||"\\u9910")+": "+(m2.foods||"")+"</span>").join("")+'</div></div>').join("")}

// === Photos ===
async function handlePhotoUpload(e){const f=e.target.files[0];if(!f)return;const p=localStorage.getItem("fitness_phone");if(!p)return;try{const du=await new Promise((r,j)=>{const re=new FileReader();re.onload=()=>r(re.result);re.onerror=j;re.readAsDataURL(f)});await API.post("/api/member/photos/upload",{phone:p,data_url:du,label:"\\u7b2c"+(P.length+1)+"\\u6b21\\u8bb0\\u5f55",note:new Date().toISOString().slice(0,10)});e.target.value="";await loadPhotos()}catch(e){}}
async function loadPhotos(){const p=localStorage.getItem("fitness_phone");if(!p)return;try{const d=await API.post("/api/member/photos/list",{phone:p});P=d.photos||[];renderPhotos()}catch(e){}}
function renderPhotos(){const e=document.getElementById("photoList");if(!P.length){e.innerHTML='<div class="record-empty">\\u8fd8\\u6ca1\\u6709\\u7167\\u7247\\u8bb0\\u5f55 \\U0001f4f8</div>';return}e.innerHTML=[...P].reverse().map(p=>'<div class="photo-card"><img src="'+p.data_url+'" alt="'+p.label+'" loading="lazy"><div class="photo-card-info"><span class="photo-card-label">'+p.label+'</span><span class="photo-card-date">'+p.date+'</span></div>'+(p.note?'<div class="photo-card-note">'+p.note+'</div>':'')+'<div class="photo-card-delete"><button class="photo-del-btn" onclick="deletePhoto('+p.id+')">\\u5220\\u9664</button></div></div>').join("")}
async function deletePhoto(id){const p=localStorage.getItem("fitness_phone");if(!p||!confirm("\\u786e\\u5b9a\\u5220\\u9664\\uff1f"))return;await API.post("/api/member/photos/delete",{phone:p,photo_id:id});await loadPhotos()}

// === Strength ===
async function handleStrengthSubmit(){const p=localStorage.getItem("fitness_phone");if(!p)return;const g=id=>{const v=document.getElementById(id).value.trim();return v?parseInt(v):null};const sq=g("inputSquats"),be=g("inputBench"),dl=g("inputDeadlift"),pr=g("inputPress"),pu=g("inputPullup"),no=document.getElementById("strengthNote").value.trim();if(!sq&&!be&&!dl&&!pr&&!pu){alert("\\u8bf7\\u81f3\\u5c11\\u586b\\u4e00\\u9879");return}await API.post("/api/member/strength/add",{phone:p,squats:sq,bench:be,deadlift:dl,press:pr,pullup:pu,note:no});["inputSquats","inputBench","inputDeadlift","inputPress","inputPullup"].forEach(id=>document.getElementById(id).value="");document.getElementById("strengthNote").value="";await loadStrength()}
async function loadStrength(){const p=localStorage.getItem("fitness_phone");if(!p)return;try{const d=await API.post("/api/member/strength/list",{phone:p});S=d.entries||[];renderStrength()}catch(e){}}
function renderStrength(){const e=document.getElementById("strengthList");if(!S.length){e.innerHTML='<div class="record-empty">\\u8fd8\\u6ca1\\u6709\\u529b\\u91cf\\u6570\\u636e \\U0001f4aa</div>';return}e.innerHTML=[...S].reverse().map(e=>{const cells=[{label:"\\u6df1\\u8e72",val:e.squats},{label:"\\u5367\\u63a8",val:e.bench},{label:"\\u786c\\u62c9",val:e.deadlift},{label:"\\u63a8\\u4e3e",val:e.press},{label:"\\u5f15\\u4f53",val:e.pullup}];return '<div class="strength-entry"><div class="strength-entry-header"><span class="strength-entry-date">'+e.date+'</span>'+(e.note?'<span class="strength-entry-note">'+e.note+'</span>':'')+'</div><div class="strength-entry-grid">'+cells.map(c=>'<div class="strength-entry-item"><div class="label">'+c.label+'</div><div class="value '+(c.val===null?"empty":"")+'">'+(c.val!==null?c.val+"kg":"\\u2014")+'</div></div>').join("")+'</div><button class="strength-del-btn" onclick="deleteStrength('+e.id+')">\\u5220\\u9664</button></div>'}).join("")}
async function deleteStrength(id){const p=localStorage.getItem("fitness_phone");if(!p||!confirm("\\u786e\\u5b9a\\u5220\\u9664\\uff1f"))return;await API.post("/api/member/strength/delete",{phone:p,entry_id:id});await loadStrength()}

// === Tab ===
function switchTab(t){document.querySelectorAll(".tab-btn").forEach(b=>b.classList.remove("active"));document.querySelector('.tab-btn[data-tab="'+t+'"]')?.classList.add("active");document.querySelectorAll(".tab-content").forEach(e=>e.style.display="none");document.getElementById("tab-"+t).style.display="block";if(t==="photos")loadPhotos();if(t==="strength")loadStrength();if(t==="fatigue")loadGrip();if(t==="nutrition")loadNutrition()}

// === Init ===
document.addEventListener("DOMContentLoaded",()=>{
document.getElementById("loginPhone")?.addEventListener("keydown",e=>{if(e.key==="Enter")handleLogin()});
document.getElementById("coachLoginPhone")?.addEventListener("keydown",e=>{if(e.key==="Enter")handleCoachLogin()});
document.getElementById("gripInput")?.addEventListener("keydown",e=>{if(e.key==="Enter")handleGripSubmit()});
const cs=localStorage.getItem("fitness_coach"),ms=localStorage.getItem("fitness_member");
if(cs){C=JSON.parse(cs);updateNav()}else if(ms){M=JSON.parse(ms);updateNav()}
console.log("\\U0001f98d Silver Back");
});"""

f=open("C:\\Users\\79018\\Documents\\体能训练资料库\\fitness_web\\static\\js\\app.js","w",encoding="utf-8")
f.write(js_code)
f.close()
print("OK - fresh JS written,", len(js_code), "chars")
